import { z } from 'zod';

/**
 * How strictly forge should react to rule violations.
 *
 * - `hybrid` (default): mechanical rules block, evaluator rubrics advise.
 * - `block-all`: every violation, including advisory rubric scores below
 *   `evaluator.minScore`, blocks commits and CI.
 * - `advisory-only`: nothing blocks. Useful for dry-runs and onboarding.
 *
 * The corresponding behavior is materialized at three points:
 * 1. `.husky/pre-commit` scripts generated by `@forge-kit-dev/cli`.
 * 2. `forge check` exit codes invoked from CI.
 * 3. `@forge-kit-dev/core`'s `Harness.run()` iteration/fix-loop logic.
 */
export const EnforcementLevelSchema = z.enum([
  'hybrid',
  'block-all',
  'advisory-only',
]);
export type EnforcementLevel = z.infer<typeof EnforcementLevelSchema>;

export const DEFAULT_ENFORCEMENT: EnforcementLevel = 'hybrid';
