// Generated by @forge-kit-dev/cli. Edit via `forge add`/`forge remove` and
// regenerate; manual edits are preserved only until the next `forge` run.
// Modules: module-clean-code, module-fsd, module-ddd, module-clean-arch

import forgePlugin from '@forge-kit-dev/eslint-plugin-forge';
import tsParser from '@typescript-eslint/parser';

export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/build/**',
    ],
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      '@forge-kit-dev/forge': forgePlugin,
    },
    rules: {
      "@forge-kit-dev/forge/component-max-lines": [
        "error",
        {
          "max": 50
        }
      ],
      "@forge-kit-dev/forge/no-boolean-flag-arg": "error",
      "@forge-kit-dev/forge/no-type-escape": "error",
      "max-params": [
        "error",
        3
      ],
      "no-console": [
        "error",
        {
          "allow": [
            "warn",
            "error"
          ]
        }
      ],
      "complexity": [
        "warn",
        12
      ],
      "@forge-kit-dev/forge/fsd-slice-boundary": "error",
      "@forge-kit-dev/forge/fsd-no-wildcard-reexport": "error",
      "@forge-kit-dev/forge/fsd-layer-typo": "error",
      "@forge-kit-dev/forge/ddd-entity-id": "error",
      "@forge-kit-dev/forge/clean-arch-domain-isolation": "error"
    }
  },
];
