import { chmod, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import type { EnforcementLevel } from '@forge/schemas';

export interface WriteHuskyOptions {
  repoRoot: string;
  enforcement: EnforcementLevel;
}

export interface WriteHuskyResult {
  /** Absolute path to the written hook, or null if nothing was written. */
  filePath: string | null;
  reason?: string;
}

/**
 * Install a minimal `.husky/pre-commit` hook that invokes `forge check`
 * whenever enforcement is `hybrid` or `block-all`. In `advisory-only`
 * mode we skip writing the file entirely — the whole point of that
 * mode is that commits should never fail because of forge.
 *
 * We deliberately do NOT:
 *  - Shell out to `npx husky install`. That pulls husky into every
 *    project's devDeps whether they want it or not. We just write the
 *    file and let the user opt in by running husky themselves.
 *  - Chain multiple hook entries. The goal is to produce something
 *    users can read in 5 seconds, not a configuration castle.
 */
export async function writeHuskyHook(
  opts: WriteHuskyOptions
): Promise<WriteHuskyResult> {
  if (opts.enforcement === 'advisory-only') {
    return { filePath: null, reason: 'advisory-only enforcement' };
  }
  const dir = join(opts.repoRoot, '.husky');
  await mkdir(dir, { recursive: true });
  const filePath = join(dir, 'pre-commit');
  const body = `#!/usr/bin/env sh
# Generated by @forge/cli. Runs forge's mechanical-rule gate
# before each commit. Delete or empty this file to disable.
. "$(dirname -- "$0")/_/husky.sh" 2>/dev/null || true

npx forge check
`;
  await writeFile(filePath, body, 'utf8');
  // Best-effort chmod — not all filesystems support it.
  try {
    await chmod(filePath, 0o755);
  } catch {
    // ignore — Windows / CI filesystems without exec bit
  }
  return { filePath };
}
