import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import type { Module } from '@forge-kit-dev/core';
import { resolveRuleConflicts } from '@forge-kit-dev/core';

export interface WriteEslintOptions {
  repoRoot: string;
  modules: readonly Module[];
}

export interface WriteEslintResult {
  filePath: string;
  mergedRuleCount: number;
  conflictCount: number;
}

/**
 * Merge every module's `eslintConfig()` fragment and persist the
 * result to `<repoRoot>/eslint.config.js`.
 *
 * Design notes:
 *  - We write a `.js` flat-config file because that's what ESLint 9+
 *    defaults to and what Next.js 14 projects now ship with. Writing a
 *    single-source-of-truth file beats the legacy `extends` machinery
 *    for predictability.
 *  - If the user already has an `eslint.config.js` we refuse to
 *    overwrite it and instead produce `eslint.forge.config.js` +
 *    leave a brief instruction so the user can import it from their
 *    own flat config.
 *  - `resolveRuleConflicts` from `@forge-kit-dev/core` is consulted purely for
 *    reporting; the winner's value is what lands on disk because the
 *    modules are fed in precedence order (see `loadModules`).
 */
export async function writeEslintConfig(
  opts: WriteEslintOptions
): Promise<WriteEslintResult> {
  // Collect rule fragments in the order the caller supplied them.
  // `loadModules` already sorted modules by precedence, so the last
  // write to a given rule id is the stricter one — exactly what the
  // conflict resolver would pick.
  const rules: Record<string, unknown> = {};
  for (const mod of opts.modules) {
    const fragment = mod.eslintConfig?.();
    if (!fragment) continue;
    const fragmentRules = readRules(fragment);
    if (!fragmentRules) continue;
    for (const [ruleId, value] of Object.entries(fragmentRules)) {
      rules[ruleId] = value;
    }
  }

  const conflicts = resolveRuleConflicts(opts.modules);

  const body = renderFlatConfig({
    moduleNames: opts.modules.map((m) => m.manifest.name),
    rules,
  });

  const primary = join(opts.repoRoot, 'eslint.config.js');
  const existing = await readIfExists(primary);
  const targetPath =
    existing === null
      ? primary
      : join(opts.repoRoot, 'eslint.forge.config.js');

  await mkdir(dirname(targetPath), { recursive: true });
  await writeFile(targetPath, body, 'utf8');

  return {
    filePath: targetPath,
    mergedRuleCount: Object.keys(rules).length,
    conflictCount: conflicts.length,
  };
}

function readRules(
  fragment: Record<string, unknown>
): Record<string, unknown> | undefined {
  const r = fragment['rules'];
  if (r && typeof r === 'object' && !Array.isArray(r)) {
    return r as Record<string, unknown>;
  }
  return undefined;
}

function renderFlatConfig(args: {
  moduleNames: readonly string[];
  rules: Record<string, unknown>;
}): string {
  const header = [
    '// Generated by @forge-kit-dev/cli. Edit via `forge add`/`forge remove` and',
    '// regenerate; manual edits are preserved only until the next `forge` run.',
    `// Modules: ${args.moduleNames.join(', ')}`,
    '',
  ].join('\n');

  // If no modules contributed rules, emit a valid but empty config.
  // We intentionally skip the plugin import in that case so a
  // degenerate eslint.config.js still parses without pulling in a
  // dependency the user might not have installed.
  if (Object.keys(args.rules).length === 0) {
    return `${header}
export default [];
`;
  }

  const rulesJson = JSON.stringify(args.rules, null, 2);
  // Design notes on the emitted shape:
  //   • `ignores` is a top-level "global ignores" block. ESLint 9
  //     only respects `ignores` as a global if the object has no
  //     other keys. Every forge-managed project should skip build
  //     artifacts, vendor code, and caches by default so the
  //     mechanical gate isn't drowned in noise from `.next/` or
  //     `dist/`. Users can widen this by appending their own config
  //     object — flat config arrays concatenate.
  //   • `files` on the main block is required because ESLint flat
  //     config only lints `.js/.mjs/.cjs` unless you opt into more
  //     extensions. React/Next.js projects need `.jsx`/`.tsx`
  //     coverage for forge rules to fire on UI slices.
  //   • `@typescript-eslint/parser` is wired in because every forge
  //     rule is designed for TS/JSX. Forge declares this as a peer
  //     dep of the plugin — user projects install it once and every
  //     generated config uses it. The parser itself has no rules so
  //     it doesn't interfere with the forge ruleset.
  return `${header}
import forgePlugin from '@forge-kit-dev/eslint-plugin-forge';
import tsParser from '@typescript-eslint/parser';

export default [
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/build/**',
    ],
  },
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      '@forge-kit-dev/forge': forgePlugin,
    },
    rules: ${indent(rulesJson, 4).trimStart()}
  },
];
`;
}

function indent(body: string, spaces: number): string {
  const pad = ' '.repeat(spaces);
  return body
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}

async function readIfExists(filePath: string): Promise<string | null> {
  try {
    return await readFile(filePath, 'utf8');
  } catch {
    return null;
  }
}
