// Generated by @forge/cli. Edit via `forge add`/`forge remove` and
// regenerate; manual edits are preserved only until the next `forge` run.
// Modules: module-clean-code, module-fsd

import forgePlugin from '@forge/eslint-plugin-forge';

export default [
  {
    files: ['**/*.{js,jsx,mjs,cjs,ts,tsx}'],
    plugins: {
      '@forge/forge': forgePlugin,
    },
    rules: {
      "@forge/forge/component-max-lines": [
        "error",
        {
          "max": 50
        }
      ],
      "@forge/forge/no-boolean-flag-arg": "error",
      "max-params": [
        "error",
        3
      ],
      "no-console": [
        "error",
        {
          "allow": [
            "warn",
            "error"
          ]
        }
      ],
      "complexity": [
        "warn",
        12
      ],
      "@forge/forge/fsd-slice-boundary": "error"
    }
  },
];
